<!-- /src/views/CoursesView.vue - FINAL, FEATURE-COMPLETE VERSION -->

<template>
  <!-- 
    ==========================================================================
    TEMPLATE / HTML STRUCTURE
    ==========================================================================
    This section is a direct migration of your CoursesPage.html file.
    It has been enhanced with Vue directives like `v-for` to dynamically render
    the filter buttons and the course cards based on our component's data.
  -->
  <div class="courses-page-wrapper">
    <main class="container">
      <!-- Page Header -->
      <header class="courses-header">
        <h1 class="animate-header">Explore the Academy</h1>
        <p class="animate-header">Find the perfect learning path to advance your skills and build the future with AI.</p>
      </header>

      <!-- 
        Filter Controls Section
        This UI is now fully data-driven.
      -->
      <section class="filter-controls">
        <div class="filter-group">
          <!-- 
            This 'v-for' loop automatically creates a button for each unique category
            found in our 'allCourses' data array. The list is generated by the 'uniqueCategories'
            computed property in our script.
          -->
          <button
            v-for="category in uniqueCategories"
            :key="category"
            @click="setFilter('category', category)"
            :class="{ active: currentFilters.category === category }"
            class="filter-btn"
          >
            {{ category }}
          </button>
        </div>
        <div class="filter-group">
          <!-- 
            This loop does the same for the different course levels.
            To add a new level, you would just add a course with that level to the
            'allCourses' array, and a new button would appear automatically.
          -->
          <button
            v-for="level in uniqueLevels"
            :key="level"
            @click="setFilter('level', level)"
            :class="{ active: currentFilters.level === level }"
            class="filter-btn"
          >
            {{ level }}
          </button>
        </div>
      </section>

      <!-- 
        Course Grid Section
        This grid is now fully reactive. It will automatically update whenever the filters change.
      -->
      <section class="courses-grid">
        <!-- 
          This 'template' tag with 'v-if' is a conditional rendering block.
          The content inside will only be shown if the 'filteredCourses' array is not empty.
        -->
        <template v-if="filteredCourses.length > 0">
          <div v-for="course in filteredCourses" :key="course.id" class="course-card animate-on-scroll">
            <div class="course-card-image-container">
              <img :src="course.imageUrl" :alt="course.title" class="course-card-image" loading="lazy">
            </div>
            <div class="course-card-content">
              <div class="course-card-tags">
                <span>{{ course.level }}</span>
                <span>{{ course.duration }}</span>
              </div>
              <h3 class="course-card-title">{{ course.title }}</h3>
              <p class="course-card-description">{{ course.description }}</p>
              <!-- 
                Using Vue Router's <RouterLink> for efficient client-side navigation.
                The `:to` binding creates a dynamic link for each course.
              -->
              <RouterLink :to="`/course/${course.id}`" class="btn btn-primary">View Course</RouterLink>
            </div>
          </div>
        </template>
        <!-- 
          If the 'v-if' condition is false (meaning no courses match the filters),
          this 'v-else' block will be rendered instead.
        -->
        <p v-else class="no-courses-message">
          No courses match your selected filters. Try a different combination.
        </p>
      </section>
    </main>
  </div>
</template>

<script setup>
// This is the modern Vue 3 <script setup> block. It's clean and efficient.
import { ref, computed, onMounted } from 'vue';
import { RouterLink } from 'vue-router';

// ===================================================================================
//  COMPONENT DATA & STATE
//  All data from your old CoursesPage.js is migrated here. This is the single
//  source of truth for this page's content until we connect it to a live database.
// ===================================================================================

// 'ref' creates a reactive variable. When its value changes, Vue automatically updates the template.
const allCourses = ref([
  { id: "cm-1", title: "AI for Content & Marketing Masterclass", description: "A complete A-Z guide on leveraging generative AI to 10x your content output, quality, and marketing ROI.", imageUrl: "https://images.pexels.com/photos/879109/pexels-photo-879109.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", category: "Content & Marketing", level: "Beginner", duration: "8 Hours" },
  { id: "cm-2", title: "Midjourney Mastery", description: "Go from basic prompts to creating photorealistic, brand-aligned visual assets with Midjourney.", imageUrl: "https://images.pexels.com/photos/16382800/pexels-photo-16382800/free-photo-of-a-colorful-abstract-painting-with-a-circle-in-the-middle.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", category: "Content & Marketing", level: "Intermediate", duration: "5 Hours" },
  { id: "bp-1", title: "AI for Business & Productivity", description: "Automate tedious tasks, analyze data, and supercharge your daily workflow with practical AI tools.", imageUrl: "https://images.pexels.com/photos/5668858/pexels-photo-5668858.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", category: "Business & Productivity", level: "Beginner", duration: "10 Hours" },
  { id: "bp-2", title: "Agentic Workflows with n8n", description: "Build, test, and deploy complex, multi-step AI agents that can perform tasks autonomously.", imageUrl: "https://images.pexels.com/photos/7688460/pexels-photo-7688460.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", category: "Business & Productivity", level: "Advanced", duration: "12 Hours" },
  { id: "ar-1", title: "AI for Academic Research", description: "Supercharge your literature reviews, data analysis, and paper writing with specialized AI tools.", imageUrl: "https://images.pexels.com/photos/3760067/pexels-photo-3760067.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", category: "Academia & Research", level: "Intermediate", duration: "6 Hours" },
  { id: "f-1", title: "The AI Quickstart", description: "Go from zero to creating with AI in your first hour. No experience needed.", imageUrl: "https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", category: "Foundations", level: "Beginner", duration: "1 Hour" },
]);

// This reactive object holds the current state of our filters.
const currentFilters = ref({
  category: "All",
  level: "All",
});

// ===================================================================================
//  COMPUTED PROPERTIES (The "Smart", Reactive Data)
// ===================================================================================

// This computed property automatically calculates the unique categories for our filter buttons.
// The `...new Set()` is a modern JavaScript trick to get only the unique values from an array.
const uniqueCategories = computed(() => ["All", ...new Set(allCourses.value.map(c => c.category))]);

// This computed property does the same for the levels.
const uniqueLevels = computed(() => ["All", ...new Set(allCourses.value.map(c => c.level))]);

// This is the most powerful part of the migration. This single computed property
// replaces the entire manual filtering and re-rendering logic from your old file.
// It automatically re-runs whenever 'currentFilters' changes, and Vue updates the page.
const filteredCourses = computed(() => {
  let courses = allCourses.value;
  // Filter by category if a specific category is selected
  if (currentFilters.value.category !== "All") {
    courses = courses.filter(c => c.category === currentFilters.value.category);
  }
  // Filter by level if a specific level is selected
  if (currentFilters.value.level !== "All") {
    courses = courses.filter(c => c.level === currentFilters.value.level);
  }
  return courses;
});

// ===================================================================================
//  METHODS & LIFECYCLE HOOKS
// ===================================================================================

/**
 * This method is called when a filter button is clicked. It updates our reactive state.
 * @param {string} type - The type of filter to change ('category' or 'level').
 * 'type' will be 'category' or 'level'.
 * 'value' will be the text of the button, e.g., "Beginner".
 */
function setFilter(type, value) {
  currentFilters.value[type] = value;
}

// 'onMounted' is the Vue lifecycle hook that runs right after the component is rendered.
// It is the perfect place to initialize animations.
onMounted(() => {
  initHeaderAnimation();
});

// --- Animation Functions (migrated from your old JS) ---
function initHeaderAnimation() {
  if (typeof window.anime !== 'undefined') {
    window.anime({
      targets: ".animate-header",
      translateY: [20, 0],
      opacity: [0, 1],
      delay: window.anime.stagger(150),
      duration: 800,
      easing: "easeOutExpo",
    });
  }
}
</script>

<style scoped>
/* 
  The 'scoped' attribute ensures these styles ONLY apply to this CoursesView.vue component.
  All styles below are a direct migration of your CoursesPage.css file,
  updated to use our new "Nexus Dark" design system variables.
*/

.courses-page-wrapper {
    background-color: var(--dark-navy);
    color: var(--text-secondary-light);
    padding-top: 80px; /* Offset for sticky navbar */
}

/* --- Page Header --- */
.courses-header {
    text-align: center;
    padding: 4rem 0;
    border-bottom: 1px solid var(--dark-border);
    margin-bottom: 3rem;
}
.courses-header h1 { font-size: 3rem; color: white; margin-bottom: 1rem; }
.courses-header p { font-size: 1.125rem; max-width: 600px; margin: 0 auto; }

/* --- Filter Controls --- */
.filter-controls {
    margin-bottom: 3rem;
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
}
.filter-group {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center;
    gap: 0.75rem;
}
.filter-btn {
    background-color: transparent;
    border: 1px solid var(--dark-border);
    color: var(--text-primary-light);
    padding: 0.5rem 1.25rem;
    border-radius: 99px;
    font-size: 0.875rem;
    font-weight: var(--font-semibold);
    cursor: pointer;
    transition: all 0.2s ease;
}
.filter-btn:hover {
    background-color: var(--dark-blue-card);
    border-color: var(--text-secondary-light);
}
.filter-btn.active {
    background: linear-gradient(90deg, var(--brand-bright-blue), var(--brand-aqua));
    border-color: transparent;
    color: var(--dark-navy);
}

/* --- Course Grid --- */
.courses-grid {
    display: grid;
    grid-template-columns: 1fr;
    gap: 2rem;
    padding-bottom: 6rem;
}
.no-courses-message {
    text-align: center;
    padding: 3rem;
    font-size: 1.1rem;
    color: var(--text-secondary-light);
}

/* --- Course Card (styles migrated here for encapsulation) --- */
.course-card {
    background-color: var(--dark-blue-card);
    border: 1px solid var(--dark-border);
    border-radius: 12px;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}
.course-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 15px 30px rgba(0, 0, 0, 0.2);
}
.course-card-image-container { height: 200px; }
.course-card-image { width: 100%; height: 100%; object-fit: cover; }
.course-card-content { padding: 1.5rem; flex: 1; display: flex; flex-direction: column; }
.course-card-tags { display: flex; gap: 0.5rem; margin-bottom: 1rem; }
.course-card-tags span {
    font-size: 0.75rem;
    padding: 0.25rem 0.75rem;
    background-color: var(--dark-blue-bg);
    border-radius: 99px;
    color: var(--text-primary-light);
}
.course-card-title { font-size: 1.25rem; margin-bottom: 0.5rem; }
.course-card-description { flex: 1; margin-bottom: 1.5rem; }
.course-card .btn { width: 100%; text-align: center; }

/* --- Responsive Styles --- */
@media (min-width: 768px) {
    .courses-header { padding: 5rem 0; }
    .courses-header h1 { font-size: 4rem; }
    .filter-controls { flex-direction: row; justify-content: center; }
    .courses-grid { grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); }
}
</style>